#!/usr/bin/env python3
"""Configure a checkout to share the main repository's Cargo artifacts and sccache."""

import argparse
import hashlib
import io
import json
import os
import platform
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
from pathlib import Path

SCCACHE_VERSION = "0.18.0"
MARKER = "# Generated by scripts/cargo-setup.py; run make cargo-setup to refresh.\n"


def repository_paths(directory):
    checkout = Path(subprocess.check_output(
        ["git", "rev-parse", "--show-toplevel"], cwd=directory, text=True,
    ).strip()).resolve()
    common = Path(subprocess.check_output(
        ["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
        cwd=checkout, text=True,
    ).strip())
    main = common.parent.resolve()
    if not (main / "Cargo.toml").is_file():
        raise RuntimeError("Expected a non-bare repository with .git in the main checkout")
    return checkout, main


def platform_target():
    machine = {"arm64": "aarch64", "AMD64": "x86_64"}.get(platform.machine(), platform.machine())
    system = {"Darwin": "apple-darwin", "Windows": "pc-windows-msvc", "Linux": "unknown-linux-musl"}
    if machine not in {"aarch64", "x86_64"} or platform.system() not in system:
        raise RuntimeError("No supported prebuilt sccache for this platform")
    return f"{machine}-{system[platform.system()]}"


def tool_path(main):
    name = "sccache.exe" if os.name == "nt" else "sccache"
    return main / "dist/tools/sccache" / SCCACHE_VERSION / platform_target() / name


def download(url):
    with urllib.request.urlopen(url, timeout=120) as response:
        return response.read()


def install(main):
    executable = tool_path(main)
    if executable.is_file():
        return
    archive_name = f"sccache-v{SCCACHE_VERSION}-{platform_target()}.tar.gz"
    url = f"https://github.com/mozilla/sccache/releases/download/v{SCCACHE_VERSION}/{archive_name}"
    archive = download(url)
    expected = download(url + ".sha256").decode("ascii").split()[0]
    if hashlib.sha256(archive).hexdigest() != expected:
        raise RuntimeError("sccache archive checksum mismatch")
    # Read only the executable; never extract archive-provided paths to disk.
    with tarfile.open(fileobj=io.BytesIO(archive), mode="r:gz") as tar:
        member = tar.getmember(f"{archive_name.removesuffix('.tar.gz')}/{executable.name}")
        if not member.isfile():
            raise RuntimeError("sccache archive executable is not a regular file")
        content = tar.extractfile(member).read()
    executable.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=executable.parent, delete=False) as temporary:
        temporary.write(content)
    staging = Path(temporary.name)
    try:
        staging.chmod(0o755)
        staging.replace(executable)
    finally:
        staging.unlink(missing_ok=True)


def config_text(main):
    values = {
        "SCCACHE_DIR": str(main / "dist/cache/sccache"),
        "SCCACHE_CACHE_SIZE": "5G",
        "TMPDIR": str(main / "dist/tools/tmp/sccache"),
        "TEMP": str(main / "dist/tools/tmp/sccache"),
        "TMP": str(main / "dist/tools/tmp/sccache"),
        # Use a repo-specific port rather than the shared default server.
        "SCCACHE_SERVER_PORT": str(20000 + int(hashlib.sha256(str(main).encode()).hexdigest()[:8], 16) % 30000),
    }
    lines = [MARKER.rstrip(), "[build]", f"target-dir = {json.dumps(str(main / 'target'), ensure_ascii=False)}",
             f"rustc-wrapper = {json.dumps(str(tool_path(main)), ensure_ascii=False)}",
             'rustc-workspace-wrapper = ""', "incremental = false", "", "[env]"]
    for key, value in values.items():
        lines.append(f"{key} = {{ value = {json.dumps(value, ensure_ascii=False)}, force = true }}")
    return "\n".join(lines) + "\n"


def ensure_managed(checkout):
    directory = checkout / ".cargo"
    path = directory / "config.toml"
    if (directory / "config").exists() or (path.exists() and not path.read_text(encoding="utf-8").startswith(MARKER)):
        raise RuntimeError(f"Refusing to replace existing Cargo config in {directory}; back it up and remove it before setup")
    return path


def configure(directory):
    """@cc [owner:mixxorz,label:tooling] cargo-worktree-shared-cache
    Setup MUST point the checkout at the main checkout's target directory and repo-local sccache.
    Setup MUST NOT replace an unmanaged Cargo config or delete existing build artifacts.
    """
    checkout, main = repository_paths(directory)
    path = ensure_managed(checkout)
    install(main)
    (main / "dist/tools/tmp/sccache").mkdir(parents=True, exist_ok=True)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(config_text(main), encoding="utf-8")
    # Older branches may not yet ignore the generated file; excludes are shared by worktrees.
    exclude = main / ".git/info/exclude"
    exclude.parent.mkdir(parents=True, exist_ok=True)
    existing = exclude.read_text(encoding="utf-8") if exclude.exists() else ""
    if "/.cargo/config.toml" not in existing.splitlines():
        with exclude.open("a", encoding="utf-8") as stream:
            stream.write("\n# Generated checkout-local Cargo setup\n/.cargo/config.toml\n")
    return main


def check(directory, env):
    """@cc [owner:mixxorz,label:tooling] cargo-worktree-config-check
    Local checks MUST reject missing or mismatched generated configuration, missing sccache, and
    environment overrides that change the shared target, compiler wrapper, or incremental policy.
    """
    checkout, main = repository_paths(directory)
    path = checkout / ".cargo/config.toml"
    if not path.is_file() or path.read_text(encoding="utf-8") != config_text(main) or not tool_path(main).is_file():
        raise RuntimeError("Shared Cargo setup is missing or outdated; run make cargo-setup")
    ensure_managed(checkout)
    expected = {
        "CARGO_TARGET_DIR": str(main / "target"),
        "CARGO_BUILD_TARGET_DIR": str(main / "target"),
        "RUSTC_WRAPPER": str(tool_path(main)),
        "CARGO_BUILD_RUSTC_WRAPPER": str(tool_path(main)),
        "CARGO_INCREMENTAL": "0",
        "CARGO_BUILD_INCREMENTAL": "false",
        "RUSTC_WORKSPACE_WRAPPER": "",
        "CARGO_BUILD_RUSTC_WORKSPACE_WRAPPER": "",
    }
    for key, value in expected.items():
        if key in env and env[key] != value:
            raise RuntimeError(f"{key} override conflicts with shared Cargo setup; unset it")
    if "SCCACHE_SERVER_UDS" in env:
        raise RuntimeError("SCCACHE_SERVER_UDS override conflicts with the repo-local server; unset it")
    for key, value in env.items():
        if key not in {"RUSTFLAGS", "CARGO_ENCODED_RUSTFLAGS", "CARGO_BUILD_RUSTFLAGS"} and not (
            key.startswith("CARGO_TARGET_") and key.endswith("_RUSTFLAGS")
        ):
            continue
        flags = value.split("\x1f") if key == "CARGO_ENCODED_RUSTFLAGS" else value.split()
        for index, flag in enumerate(flags):
            option = ""
            if flag in {"-C", "--codegen"} and index + 1 < len(flags):
                option = flags[index + 1]
            else:
                for prefix in ["-C=", "-C", "--codegen="]:
                    if flag.startswith(prefix):
                        option = flag[len(prefix):]
                        break
            if option.partition("=")[0] == "incremental":
                raise RuntimeError(f"{key} override enables incremental compilation; unset that flag")


def run():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify setup without installing or writing files")
    args = parser.parse_args()
    if args.check:
        check(Path.cwd(), os.environ)
    else:
        main = configure(Path.cwd())
        check(Path.cwd(), os.environ)
        print(f"Shared Cargo target: {main / 'target'}")
        print(f"sccache: {tool_path(main)} (5G cache in {main / 'dist/cache/sccache'})")


if __name__ == "__main__":
    try:
        run()
    except (OSError, ValueError, RuntimeError, subprocess.CalledProcessError, tarfile.TarError) as error:
        print(f"Cargo setup failed: {error}", file=sys.stderr)
        sys.exit(1)
